# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
 
steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'rsolsonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'validatiebackend'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectName=validatiebackend
      sonar.projectKey=validatiebackend
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Backend/ValidatieBackend/ValidatieBackend/ValidatieBackend.csproj'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Backend/ValidatieBackend/ValidatieBackend/ValidatieBackend.csproj'
    arguments: '-r win-x86 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'