# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
 
steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'rsolsonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'validatiepoc'
    extraProperties: |
      sonar.projectName=validatiepoc
      sonar.projectKey=validatiepoc
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
